// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFQV-34rlT_KGBZhsEa6p6u89DNruRSD8',
    appId: '1:13937493589:web:42f77a78d94329458736dc',
    messagingSenderId: '13937493589',
    projectId: 'easyshoping-app1',
    authDomain: 'easyshoping-app1.firebaseapp.com',
    storageBucket: 'easyshoping-app1.appspot.com',
    measurementId: 'G-FB8V05YEC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSfN64QnZRuX-BStJgWn9I7V-UEFvvaqI',
    appId: '1:13937493589:android:a904646e89c2ef2c8736dc',
    messagingSenderId: '13937493589',
    projectId: 'easyshoping-app1',
    storageBucket: 'easyshoping-app1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB51W7Y-mYTI6nOMqwoxsfnd_j5HuSaOTw',
    appId: '1:13937493589:ios:93775b8ebaeb7a4e8736dc',
    messagingSenderId: '13937493589',
    projectId: 'easyshoping-app1',
    storageBucket: 'easyshoping-app1.appspot.com',
    iosBundleId: 'com.example.complainManagementSystem',
  );
}
